
MPlayer 0.50  (C) 2000-2001 Arpad Gereoffy (see DOCS!)

Reading /home/alone/.mplayer/codecs.conf: can't open '/home/alone/.mplayer/codecs.conf': No such file or directory
Reading /usr/local/share/mplayer/codecs.conf: 18 audio & 40 video codecs
font: can't open file: /home/alone/.mplayer/font/font.desc
Font /usr/local/share/mplayer/font/font.desc loaded successfully! (206 chars)
Playing msnaudio.asf
Detected ASF file format!
VIDEO:  [MP42]  320x240  24bpp
[V] filefmt:6  fourcc:0x3234504D  size:320x240  fps:1000.00  ftime:=0.0010
Detected audio codec: [msgsmacm] drv:4 (MS GSM)
Loading DLL: 'msgsm32.acm'
Loading DLL: 'msgsm32.acm'
Loading DLL: 'msgsm32.acm'
ACM_Decoder: Unappropriate audio format
Could not load/initialize Win32/ACM AUDIO codec (missing DLL file?)
Couldn't initialize audio codec! -> nosound
Detected video codec: [mpeg4] drv:2 (Microsoft MPEG-4 v1/v2)
Loading DLL: 'mpg4c32.dll'
Movie-Aspect is undefined - no prescaling applied.
VO: [xv] 320x240 => 320x240 Packed YUY2 
vo: X11 running at 1024x768 with depth 16 and 16 bits/pixel (":0.0" => local display)
Xvideo image format: 0x32595559 (YUY2) packed
Xvideo image format: 0x32315659 (YV12) planar
Xvideo image format: 0x59565955 (UYVY) packed
Xvideo image format: 0x30323449 (I420) planar
using Xvideo port 48 for hw scaling
[xv] dcx: 1 dcy: 23 dx: 0 dy: 0 dw: 320 dh: 240
Disabling DPMS
stat: 1
Audio: no sound!!!
Start playing...

